name: food_delivery
description: "A new Flutter project."

# Prevent accidental publication to pub.dev
publish_to: 'none'

# Version and build number
version: 1.0.0+1

# Flutter SDK environment
environment:
  sdk: ">=3.5.0 <4.0.0"

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  curved_labeled_navigation_bar: ^2.0.5
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# Flutter-specific configurations
flutter:
  uses-material-design: true

  # Asset configuration
  assets:
    - images/

  # Custom fonts
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-SemiBold.ttf
